application: map-of-life
module: location
runtime: python27
threadsafe: true
api_version: 1
skip_files:
- ^(node_modules/.*)
- ^(client/components/mol/?.*/node_modules/.*)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yml$
- ^(.*/)?.*\.map$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.sass$
- ^(.*/)?.*\.gzip$
- ^(.*/)?.*\.rb$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\LICENSE$
- ^(.*/)?.*\.coffee$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

# MOL REST APIs

- url: /api/refine
  script: server.handlers.refine_handler.application

- url: /api/refine/run_analysis
  script: server.handlers.refine_analysis_handler.application

- url: /api/protect
  script: server.handlers.protect_handler.application

- url: /api/protect/run_analysis
  script: server.handlers.protect_analysis_handler.applicationserver.handlers.

- url: /api/change
  script: server.handlers.change_handler.application

- url: /api/change/run_analysis
  script: server.handlers.change_analysis_handler.application

- url: /api/pop_change
  script: server.handlers.server.handlers.pop_change_handler.application

- url: /api/year
  script: server.handlers.year_handler.application

- url: /api/services/.*
  script: server.handlers.services_handler.application

- url: /api/map/.*
  script: server.handlers.carto_tile_handler.application

- url: /api/tile/.*
  script: server.handlers.tile_handler.application

- url: /app
  static_dir: client

- url: /client
  static_dir: client

# Boots the angular application

- url: /location/.*
  script: server.handlers.base_handler.application

- url: /location
  script: server.handlers.base_handler.application

- url: /species/.*
  script: server.handlers.base_handler.application

- url: /species
  script: server.handlers.base_handler.application


libraries:
- name: pycrypto
  version: "2.3"

- name: numpy
  version: "latest"

- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

- name: matplotlib
  version: latest
