application: map-of-life
module: location
version: production
runtime: python27
threadsafe: true
api_version: 1
skip_files:
- ^(node_modules/.*)
- ^(client/components/mol/?.*/node_modules/.*)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yml$
- ^(.*/)?.*\.map$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.sass$
- ^(.*/)?.*\.gzip$
- ^(.*/)?.*\.rb$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\LICENSE$
- ^(.*/)?.*\.coffee$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

# MOL REST APIs

- url: /location/assets/
  static_dir: client
  secure: always

# Boots the angular application

- url: /location/.*
  script: server.handlers.base.application
  secure: always

- url: /location
  script: server.handlers.base.application
  secure: always

- url: /.*
  script: server.handlers.base.application
  secure: always

- url: /
  script: server.handlers.base.application
  secure: always


libraries:
- name: pycrypto
  version: "2.3"

- name: numpy
  version: "latest"

- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

- name: matplotlib
  version: latest
